#if defined _mg_missions_api_const_included
    #endinput
#endif

#define _mg_missions_api_const_included

#define MISSIONID_CHATMLVL1             1
#define MISSIONID_CHATMLVL2             2
#define MISSIONID_CHATMLVL3             3
#define MISSIONID_CHATMLVL4             4
#define MISSIONID_CHATMLVL5             5
#define MISSIONID_DAMAGEMLVL1           6
#define MISSIONID_DAMAGEMLVL2           7
#define MISSIONID_DAMAGEMLVL3           8
#define MISSIONID_DAMAGEMLVL4           9
#define MISSIONID_DAMAGEMLVL5           10
#define MISSIONID_KILLMLVL1             11
#define MISSIONID_KILLMLVL2             12
#define MISSIONID_KILLMLVL3             13
#define MISSIONID_KILLMLVL4             14
#define MISSIONID_FIRSTJUMPM            15
#define MISSIONID_TIMEMLVL1             16
#define MISSIONID_TIMEMLVL2             17
#define MISSIONID_TIMEMLVL3             18
#define MISSIONID_TIMEMLVL4             19
#define MISSIONID_TIMEMLVL5             20
#define MISSIONID_TIMEMLVL6             21
#define MISSIONID_CAPTUREFLAGMLVL1      22
#define MISSIONID_CAPTUREFLAGMLVL2      23
#define MISSIONID_CAPTUREFLAGMLVL3      24
#define MISSIONID_CAPTUREFLAGMLVL4      25
#define MISSIONID_WINNERTEAMMLVL1       26
#define MISSIONID_WINNERTEAMMLVL2       27
#define MISSIONID_WINNERTEAMMLVL3       28
#define MISSIONID_WINNERTEAMMLVL4       29
#define MISSIONID_FLAGBACKMLVL1         30
#define MISSIONID_FLAGBACKMLVL2         31
#define MISSIONID_FLAGBACKMLVL3         32
#define MISSIONID_LAST          MISSIONID_FLAGBACKMLVL3
#define MISSIONID_BLOCKSIZE     MISSIONID_LAST + 1