#if defined _mg_missions_api_const_included
    #endinput
#endif

#define _mg_missions_api_const_included

#define MISSIONID_CHATMLVL1     1
#define MISSIONID_CHATMLVL2     2
#define MISSIONID_CHATMLVL3     3
#define MISSIONID_CHATMLVL4     4
#define MISSIONID_CHATMLVL5     5
#define MISSIONID_DAMAGEMLVL1   6
#define MISSIONID_DAMAGEMLVL2   7
#define MISSIONID_DAMAGEMLVL3   8
#define MISSIONID_DAMAGEMLVL4   9
#define MISSIONID_DAMAGEMLVL5   10
#define MISSIONID_KILLMLVL1     11
#define MISSIONID_KILLMLVL2     12
#define MISSIONID_KILLMLVL3     13
#define MISSIONID_KILLMLVL4     14
#define MISSIONID_LAST          MISSIONID_KILLMLVL4
#define MISSIONID_BLOCKSIZE     MISSIONID_LAST + 1