#if defined _zi_core_const_included
	#endinput
#endif

#define _zi_core_const_included

#define ZI_CLASS_NONE			0

#define ZI_HMCLASS_NORMAL		1

#define ZI_ZMCLASS_NORMAL		1

#define ZI_ZMSUBCLASS_NORMAL1	1
#define ZI_ZMSUBCLASS_NORMAL2	2
#define ZI_ZMSUBCLASS_NORMAL3	3
#define ZI_ZMSUBCLASS_NORMAL4	4
#define ZI_ZMSUBCLASS_NORMAL5	5
#define ZI_ZMSUBCLASS_NORMAL6	6

#define ZI_HRCLASS_NEMESIS		1

#define ZI_GMTYPE_NONE			0
#define ZI_GMTYPE_NORMAL		1
#define ZI_GMTYPE_MULTIPLE		2
#define ZI_GMTYPE_HERO			3
#define ZI_GMTYPE_ARMAGEDDON	4

#define ZI_GAMEMODE_NONE		0

#define ZI_TEAM_ZOMBIE			CS_TEAM_T
#define ZI_TEAM_HUMAN			CS_TEAM_CT

#define ZI_ARMOR_TYPE			CS_ARMOR_KEVLAR