#if defined _mg_zi_core_const_included
	#endinput
#endif

#define _mg_zi_core_const_included

#define ZI_CLASS_NONE			0

#define ZI_HMCLASS_NORMAL		1

#define ZI_ZMCLASS_NORMAL		1

#define ZI_ZMSUBCLASS_NORMAL1	1
#define ZI_ZMSUBCLASS_NORMAL2	2
#define ZI_ZMSUBCLASS_NORMAL3	3
#define ZI_ZMSUBCLASS_NORMAL4	1
#define ZI_ZMSUBCLASS_NORMAL5	1
#define ZI_ZMSUBCLASS_NORMAL6	1

#define ZI_HRCLASS_NEMESIS		1